#!/bin/bash

#
# Community Edition build script
#

set -e

if [[ -n "$1" ]]
then
	if [[ "$1" == "win" || "$1" == "lin" || "$1" == "mac" ]]
	then 
		arch=$1
	else
		echo "Unknown arch value, try: win, lin or mac"
		exit
	fi
else
	echo "Missing Argument: arch"
	exit
fi

if [[ "$2" != "noclean" ]]
then make clean
fi

if [[ "$arch" == "win" ]]
then 
	cp -r pak comed
	mkdir -p comed/bin
	mkdir -p comed/bin64
	cp INSTALL.md comed/INSTALL.txt
	make PREFIX=i686-w64-mingw32
	mv sauerbraten.exe comed/bin/sauerbraten.exe
	make clean
	make PREFIX=x86_64-w64-mingw32
	mv sauerbraten.exe comed/bin64/sauerbraten.exe
	zip -r comed-nightly-windows.zip comed
	rm -r comed
fi

if [[ "$arch" == "lin" ]]
then 
	cp -r pak comed
	mkdir -p comed/bin_unix
	cp INSTALL.md comed/INSTALL.txt
	make PREFIX=i686-unknown-linux-gnu
	mv sauer_client comed/bin_unix/linux_client
	make clean
	make PREFIX=x86_64-unknown-linux-gnu
	mv sauer_client comed/bin_unix/linux_64_client
	zip -r comed-nightly-linux.zip comed
	rm -r comed
fi

if [[ "$arch" == "mac" ]]
then 
	echo ""
	echo "using osxcross crosscompiler suite to build" 
	echo "see http://github.com/tpoechtrager/osxcross"
	echo ""
	cp -r pak comed
	cp INSTALL.md comed/INSTALL.txt
	eval $(osxcross-conf 2>/dev/null)
	make PREFIX=x86_64-apple-$OSXCROSS_TARGET
	mv sauerbraten comed/
	zip -r comed-nightly-osx.zip comed
	rm -r comed
fi

echo ""
echo "Archive created, hopefully. :)"
echo "Have fun with the Sauerbraten Community Edition!"
