#!/bin/bash

#
# Community Edition build script
#

if [[ -n "$1" ]]
then
	if [[ "$1" == "win" || "$1" == "lin" || "$1" == "mac" ]]
	then 
		arch=$1
	else
		echo "Unknown arch, try: win, lin or mac"
		exit
	fi
else
	echo "Missing Argument: arch"
	exit
fi

pushd src
make clean

if [[ "$arch" == "win" ]]
then 
	cp -r ../pak comed
	mkdir comed/bin
	mkdir comed/bin64
	cp INSTALL.txt comed/install.txt
	make PREFIX=i686-w64-mingw32
	mv sauerbraten.exe comed/bin/sauerbraten.exe
	make clean
	make PREFIX=x86_64-w64-mingw32
	mv sauerbraten.exe comed/bin64/sauerbraten.exe
	zip -r comed-nightly-windows.zip comed
	mv comed-nightly-windows.zip ../
	rm -r comed
fi

if [[ "$arch" == "lin" ]]
then 
	cp -r ../pak comed
	mkdir comed/bin_unix
	cp INSTALL.lin comed/install.txt
	echo ""
	echo "WARNING"
	echo "Linux32 is not supported yet."
	echo ""
	#make PREFIX=i686-unknown-linux-gnu
	#mv sauer_client comed/bin_unix/linux_client
	#make clean
	make PREFIX=x86_64-unknown-linux-gnu
	mv sauer_client comed/bin_unix/linux_64_client
	tar czf comed-nightly-linux.tar.gz comed
	mv comed-nightly-linux.tar.gz ../
	rm -r comed
fi

if [[ "$arch" == "mac" ]]
then 
	echo "note, this fails on darwin kernels > 13.2.0, e.g. osX 10.9"
	cp -r ../pak/ comed
	cp INSTALL.osx comed/install.txt
	make clean
	make PREFIX=x86_64-apple-darwin13.2.0
	mv sauerbraten comed/
	tar czf comed-nightly-osx.tar.gz comed
	mv comed-nightly-osx.tar.gz ../ 
	rm comed
fi
popd
echo ""
echo "Archive created, hopefully. :)"
echo "Have fun with the Sauerbraten Community Edition!"