#!/bin/bash

#
# Community Edition build script
#

if [[ -n "$1" ]]
then
	if [[ "$1" == "win" || "$1" == "lin" || "$1" == "mac" || "$1" == "macX" ]]
	then 
		arch=$1
	else
		echo "Unknown arch value, try: win, lin, mac or macX"
		exit
	fi
else
	echo "Missing Argument: arch"
	exit
fi

if [[ "$2" != "noclean" ]]
then make clean
fi

if [[ "$arch" == "win" ]]
then 
	cp -r pak comed
	mkdir comed/bin
	mkdir comed/bin64
	cp INSTALL.md comed/INSTALL.txt
	make PREFIX=i686-w64-mingw32
	mv sauerbraten.exe comed/bin/sauerbraten.exe
	make PREFIX=x86_64-w64-mingw32
	mv sauerbraten.exe comed/bin64/sauerbraten.exe
	zip -r comed-nightly-windows.zip comed
	rm -r comed
fi

if [[ "$arch" == "lin" ]]
then 
	cp -r pak comed
	mkdir comed/bin_unix
	cp INSTALL.md comed/INSTALL.txt
	make PREFIX=i686-unknown-linux-gnu
	mv sauer_client comed/bin_unix/linux_client
	make PREFIX=x86_64-unknown-linux-gnu
	mv sauer_client comed/bin_unix/linux_64_client
	zip -r comed-nightly-linux.zip comed
	rm -r comed
fi

if [[ "$arch" == "mac" ]]
then 
	echo ""
	echo "note: this fails on darwin kernels > 13.2.0, e.g. OS X 10.9"
	echo "quickfix should be to rename the deps/*darwin* dir to the propper version number"
	echo ""
	cp -r pak comed
	cp INSTALL.md comed/INSTALL.txt
	make PREFIX=x86_64-apple-darwin13.2.0
	mv sauerbraten comed/
	zip -r comed-nightly-osx.zip comed
	rm -r comed
fi

if [[ "$arch" == "macX" ]]
then 
	echo ""
	echo "using osxcross crosscompiler suite to build" 
	echo "see http://github.com/tpoechtrager/osxcross"
	echo ""
	cp -r pak comed
	cp INSTALL.md comed/INSTALL.txt
	make CXX=x86_64-apple-darwin13-clang++ CC=x86_64-apple-darwin13-clang PREFIX=x86_64-apple-darwin13 STRIP=x86_64-apple-darwin13-strip
	mv sauerbraten comed/
	zip -r comed-nightly-osx.zip comed
	rm -r comed
fi

echo ""
echo "Archive created, hopefully. :)"
echo "Have fun with the Sauerbraten Community Edition!"